CREATE TABLE simulation_runs (
    id UUID PRIMARY KEY,
    scenario_id VARCHAR(64) NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    first_stressed INTEGER,
    first_degraded INTEGER,
    recovery_time INTEGER,
    final_deficit INTEGER NOT NULL,
    cascade_events INTEGER NOT NULL,
    decision_debt BOOLEAN NOT NULL,
    verified BOOLEAN NOT NULL,
    fingerprint VARCHAR(64) NOT NULL,
    client_first_stressed INTEGER,
    client_first_degraded INTEGER,
    client_recovery_time INTEGER,
    client_final_deficit INTEGER NOT NULL,
    command_count INTEGER NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_simulation_runs_recorded_at ON simulation_runs(recorded_at DESC);
CREATE INDEX idx_simulation_runs_verified ON simulation_runs(verified);
CREATE INDEX idx_simulation_runs_fingerprint ON simulation_runs(fingerprint);

CREATE TABLE run_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id UUID NOT NULL,
    simulation_second INTEGER NOT NULL,
    command_id VARCHAR(32) NOT NULL,
    report_id VARCHAR(32),
    insertion_order INTEGER NOT NULL,
    CONSTRAINT fk_run_commands_run FOREIGN KEY (run_id) REFERENCES simulation_runs(id) ON DELETE CASCADE,
    CONSTRAINT uq_run_commands_order UNIQUE (run_id, simulation_second, insertion_order)
);

CREATE INDEX idx_run_commands_run_id ON run_commands(run_id);
