import { commandBlock, commitCommand, deficit, freshState, stepSimulation, systems, edges, commandDefs } from '../src/engine'
let passed = 0
const check = (condition: unknown, label: string) => { if (!condition) throw new Error(`FAIL: ${label}`); passed++ }
const run = (commands: string[]) => { let s = { ...freshState(), running: true }; for (const id of commands) { const blocked = commandBlock(id, s); if (!blocked) s = commitCommand(s, id) } while (!s.ended) s = stepSimulation(s); return s }
const summary = (commands: string[]) => { const s=run(commands); const cascades=s.log.filter(e=>e.kind==='CASCADE'); return {s, stressed:cascades.find(e=>e.text.includes('STRESSED'))?.time??null, degraded:cascades.find(e=>e.text.includes('DEGRADED'))?.time??null, recovery:s.recoveryTime??null, final:deficit(s), backup:s.log.find(e=>e.kind==='DEBT ACTIVE'&&e.causeId==='telecom-backup-depletion')?.time??null} }
const n=summary([]), r=summary(['reroute']), rm=summary(['reroute','mobile']), sh=summary(['shed'])
check(n.stressed===40,'no action first stressed'); check(n.degraded===185,'no action first degraded'); check(n.recovery===null,'no action no recovery'); check(n.final===120,'no action deficit');
check(r.stressed===76,'reroute first stressed'); check(r.degraded===null,'reroute no degraded'); check(r.recovery===null,'reroute no full recovery'); check(r.final===40,'reroute deficit');
check(rm.stressed===null,'reroute+mobile no stressed'); check(rm.degraded===null,'reroute+mobile no degraded'); check(rm.recovery===40,'reroute+mobile recovery'); check(rm.final===0,'reroute+mobile deficit');
check(sh.stressed===180,'shed first stressed'); check(sh.degraded===198,'shed first degraded'); check(sh.recovery===null,'shed no recovery'); check(sh.final===30,'shed deficit'); check(sh.backup===180,'shed backup depletion');
check(systems.length===6,'six systems'); check(edges.length===8,'eight dependencies'); check(commandDefs.length===6,'six interventions');
const f=freshState(); check(f.time===0,'initial time'); check(!f.running,'initial stopped'); check(!f.ended,'initial not ended'); check(deficit(f)===120,'initial deficit'); check(f.resources.reserve===72,'reserve'); check(f.resources.mobile===2,'mobile'); check(f.resources.teams===2,'teams'); check(f.resources.slots===2,'slots'); check(f.resources.intel===2,'intel'); check(f.reports.length===4,'reports'); check(f.log.length===1,'initial event'); check(f.values.Power.generation===920,'generation'); check(f.values.Power.demand===1040,'demand'); check(commandBlock('mobile',{...f,running:true})==='','mobile allowed'); check(commandBlock('shed',{...f,running:true})==='','shed allowed'); check(commandBlock('reroute',{...f,running:true})==='','reroute allowed'); check(commandBlock('verify',{...f,running:true},f.reports[0])==='','verify allowed'); check(commandBlock('repair',{...f,running:true},f.reports[2])==='','repair allowed'); check(commandBlock('unknown',{...f,running:true}).includes('unknown'),'unknown blocked');
console.log(`Assertions: ${passed}/39 PASS`)
